version: "3.8"

services:

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=sa

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    networks:
     - innova
  
  configserver:
    image: innova/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - innova
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
   
  eurekaserver:
    image: innova/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - innova
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
  order:
    image: innova/order:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - innova
    depends_on:
      - configserver
      - eurekaserver
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  
  product:
    image: innova/product:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - innova
    depends_on:
      - configserver
      - eurekaserver
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
    
  gatewayserver:
    image: innova/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - innova
    depends_on:
      - configserver
      - eurekaserver
      - order
      - product
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
      
networks:
  innova: